baseURL = 'https://cptjackharkness.github.io/'
languageCode = 'en'
title = 'Ricardo Ribeiro | Cybersecurity'
theme = 'hugo-theme-stack'

[params]
    description = 'Cybersecurity & SOC Analysis Portfolio'
    showPoweredBy = false

[params.sidebar]
    subtitle = 'Cybersecurity Student | Future SOC Analyst'
    emoji = '🎯'
    avatar = 'image/foto_perfil.jpg' # 

[[params.social]]
    name = "linkedin"
    icon = "brand-linkedin"
    url = "https://www.linkedin.com/in/ricardo-ribeiro-2277ab23b/"

[[params.social]]
    name = "github"
    icon = "brand-github"
    url = "https://github.com/CptJackHarkness"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
    params = { icon = "home" }

[[menu.main]]
    name = "Homelab"
    url = "/categories/homelab/"
    weight = 20
    params = { icon = "server" }

[[menu.main]]
    name = "CTFs"
    url = "/categories/ctfs/"
    weight = 30
    params = { icon = "flag" }

[[menu.main]]
    name = "Wargaming"
    url = "/categories/wargaming/"
    weight = 40
    params = { icon = "terminal" }