baseURL = 'https://cptjackharkness.github.io/'
languageCode = 'en'
title = 'Ricardo Ribeiro | Cybersecurity'
theme = 'hugo-theme-stack'

[params]
    description = 'Cybersecurity & SOC Analysis Portfolio'
    showPoweredBy = false

[params.sidebar]
    subtitle = 'Cybersecurity Student | Future SOC Analyst'
    emoji = '🎯'
    avatar = 'image/foto_perfil.jpg' # 

[[params.social]]
    name = "linkedin"
    icon = "brand-linkedin"
    url = "https://www.linkedin.com/in/ricardo-ribeiro-2277ab23b/"

[[params.social]]
    name = "github"
    icon = "brand-github"
    url = "https://github.com/CptJackHarkness"

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
    [menu.main.params]
        icon = "home"

[[menu.main]]
    identifier = "homelab"
    name = "Homelab"
    url = "/categories/homelab/"
    weight = 20
    [menu.main.params]
        icon = "server"

[[menu.main]]
    identifier = "ctfs"
    name = "CTFs"
    url = "/categories/ctfs/"
    weight = 30
    [menu.main.params]
        icon = "flag"

[[menu.main]]
    identifier = "wargaming"
    name = "Wargaming"
    url = "/categories/wargaming/"
    weight = 40
    [menu.main.params]
        icon = "terminal"

[[menu.main]]
    identifier = "quick-writeups"
    name = "Quick Writeups"
    url = "/categories/quick-writeups/"
    weight = 50
    [menu.main.params]
        icon = "bolt"

[params.colorScheme]
    default = "dark"
    toggle = false